app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Templates
Route::pattern('id', '[0-9]+');
Route::pattern('page_url', '[0-9a-z-_]+');

// Dashboard
Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => 'auth'], function(){

	// Main page
	Route::get('/', 'AdminHomeController@getIndex');
	Route::post('/', 'AdminHomeController@postIndex');
	Route::post('/upload-image', 'AdminHomeController@postUploadImage');

	// Other controllers
	Route::controllers([
        'settings'				=> 'AdminSettingsController',
        'menu'					=> 'AdminMenuController',
        'pages'					=> 'AdminPagesController',
        'projects-categories'	=> 'AdminProjectsCategoriesController',
        'projects'				=> 'AdminProjectsController',
        'publications'			=> 'AdminPublicationsController',
        'about-page'			=> 'AdminAboutPageController',
        'feedbacks'				=> 'AdminFeedbacksController',
        'users'					=> 'AdminUsersController',
    ]);

	// Logout
	Route::get('auth/logout', 'Auth\AuthController@logout');
});

// Default auth
Route::controllers([
	'auth' 		=> 'Auth\AuthController',
	'password' 	=> 'Auth\PasswordController',
]);

// Frontend
Route::group(['namespace' => 'Frontend', 'prefix' => LaravelLocalization::setLocale()], function(){

	// Main page
	Route::get('/', 'HomeController@getIndex');

	// Projects category
	Route::get('/category/{page_url}', 'CategoriesController@getIndex');

	// Projects media
	foreach( ['photo', 'video', 'honors'] as $route )
	{
		Route::get('/projects-' . $route, 'ProjectsController@getMedia');
	}

	// Project
	Route::get('/project/{page_url}', 'ProjectsController@getProject');

	// Publications
	Route::get('/publications', 'PublicationsController@getIndex');

	// Page about
	Route::get('/about', 'PagesController@getAbout');

	// Page contacts
	Route::get('/contacts', 'PagesController@getContacts');
	Route::post('/contacts', 'PagesController@postContacts');

	// Other pages
	Route::get('/{page_url}', 'PagesController@getIndex');
});

app/Models/AboutPage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AboutPage extends Model
{
    protected $table = 'as_about_page';
	
	protected $guarded = [];

	// Текст для первого года
	public function getYear1TextAttribute()
	{
		$locale = \App::getLocale();
		$column = 'year_1_text_' . $locale;
		return $this->{$column};
    }

    // Текст для второго года
	public function getYear2TextAttribute()
	{
		$locale = \App::getLocale();
		$column = 'year_2_text_' . $locale;
		return $this->{$column};
    }

	// Текст для третьего года
	public function getYear3TextAttribute()
	{
		$locale = \App::getLocale();
		$column = 'year_3_text_' . $locale;
		return $this->{$column};
    }

    // Обучение и развитие (заглавие)
    public function getEducationDevTitleAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'education_dev_title_' . $locale;
		return $this->{$column};
    }

	// Обучение и развитие (текст)
    public function getEducationDevTextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'education_dev_text_' . $locale;
		return $this->{$column};
    }

    // Философия (1 текст)
    public function getPhilosophy1TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'philosophy_1_text_' . $locale;
		return $this->{$column};
    }

    // Философия (2 текст)
    public function getPhilosophy2TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'philosophy_2_text_' . $locale;
		return $this->{$column};
    }

	// Философия (3 текст)
    public function getPhilosophy3TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'philosophy_3_text_' . $locale;
		return $this->{$column};
    }

    // Философия (4 текст)
    public function getPhilosophy4TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'philosophy_4_text_' . $locale;
		return $this->{$column};
    }

    // Как мы работаем? (1 текст)
    public function getHowWork1TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'how_work_1_text_' . $locale;
		return $this->{$column};
    }

    // Как мы работаем? (2 текст)
    public function getHowWork2TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'how_work_2_text_' . $locale;
		return $this->{$column};
    }

    // Как мы работаем? (3 текст)
    public function getHowWork3TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'how_work_3_text_' . $locale;
		return $this->{$column};
    }

    // Как мы работаем? (4 текст)
    public function getHowWork4TextAttribute()
    {
    	$locale = \App::getLocale();
		$column = 'how_work_4_text_' . $locale;
		return $this->{$column};
    }
}

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    protected $table = 'as_pages';
	
	protected $guarded = [];

	// Name
	public function getNameAttribute()
	{
		$locale = \App::getLocale();
		$column = 'name_' . $locale;
		return $this->{$column};
    }

    // Annotation
	public function getAnnotationAttribute()
	{
		$locale = \App::getLocale();
		$column = 'annotation_' . $locale;
		return $this->{$column};
    }

    // Body
	public function getBodyAttribute()
	{
		$locale = \App::getLocale();
		$column = 'body_' . $locale;
		return $this->{$column};
    }
	
	// Meta title
	public function getMetaTitleAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_title_' . $locale;
		return $this->{$column};
    }
	
	// Meta keywords
	public function getMetaKeywordsAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_keywords_' . $locale;
		return $this->{$column};
    }
	
	// Meta description
	public function getMetaDescriptionAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_description_' . $locale;
		return $this->{$column};
    }

    // Upload image
    public static function upload_image( $file, $id )
    {
		if( $old_image = self::find( $id )->image )
			\File::delete( public_path() . '/uploads/pages/images/' . $old_image );
		
		$file_name = time() . '_' . \Slug::make(basename($file->getClientOriginalName(), '.' . $file->getClientOriginalExtension())) . '.' . $file->getClientOriginalExtension();
		
		\Image::make( $file )->save( 'uploads/pages/images/' . $file_name );
		
		self::find( $id )->update(['image' => $file_name]);
    }

    // Upload video file
    public static function upload_video( $file, $id )
    {
    	if( $old_video = self::find( $id )->video_file )
			\File::delete( public_path() . '/uploads/pages/video/' . $old_video );
		
		$file_name = time() . '_' . \Slug::make(basename($file->getClientOriginalName(), '.' . $file->getClientOriginalExtension())) . '.' . $file->getClientOriginalExtension();
		
		$file->move( public_path() . '/uploads/pages/video/', $file_name );

		self::find( $id )->update(['video_file' => $file_name]);
    }
}

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $table = 'as_projects';
	
	protected $guarded = [];

	// Name
	public function getNameAttribute()
	{
		$locale = \App::getLocale();
		$column = 'name_' . $locale;
		return $this->{$column};
    }

    // Object
	public function getObjectAttribute()
	{
		$locale = \App::getLocale();
		$column = 'object_' . $locale;
		return $this->{$column};
    }

    // Location
	public function getLocationAttribute()
	{
		$locale = \App::getLocale();
		$column = 'location_' . $locale;
		return $this->{$column};
    }

    // Space
	public function getSpaceAttribute()
	{
		$locale = \App::getLocale();
		$column = 'space_' . $locale;
		return $this->{$column};
    }

	// Client
	public function getClientAttribute()
	{
		$locale = \App::getLocale();
		$column = 'client_' . $locale;
		return $this->{$column};
    }
	
	// Photographer
	public function getPhotographerAttribute()
	{
		$locale = \App::getLocale();
		$column = 'photographer_' . $locale;
		return $this->{$column};
    }

    // Annotation
	public function getAnnotationAttribute()
	{
		$locale = \App::getLocale();
		$column = 'annotation_' . $locale;
		return $this->{$column};
    }

    // Body slider
	public function getBodySliderAttribute()
	{
		$locale = \App::getLocale();
		$column = 'body_slider_' . $locale;
		return $this->{$column};
    }

    // Body gallery
	public function getBodyGalleryAttribute()
	{
		$locale = \App::getLocale();
		$column = 'body_gallery_' . $locale;
		return $this->{$column};
    }

    // Body video
	public function getBodyVideoAttribute()
	{
		$locale = \App::getLocale();
		$column = 'body_video_' . $locale;
		return $this->{$column};
    }
	
	// Meta title
	public function getMetaTitleAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_title_' . $locale;
		return $this->{$column};
    }
	
	// Meta keywords
	public function getMetaKeywordsAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_keywords_' . $locale;
		return $this->{$column};
    }
	
	// Meta description
	public function getMetaDescriptionAttribute()
	{
		$locale = \App::getLocale();
		$column = 'meta_description_' . $locale;
		return $this->{$column};
    }

    // Upload video screen
    public static function upload_screen( $file, $id )
    {
		if( $old_screen = self::find( $id )->video_screen )
			\File::delete( public_path() . '/uploads/projects/video/screenshots/' . $old_screen );
		
		$file_name = time() . '_' . \Slug::make(basename($file->getClientOriginalName(), '.' . $file->getClientOriginalExtension())) . '.' . $file->getClientOriginalExtension();
		
		\Image::make( $file )->save( 'uploads/projects/video/screenshots/' . $file_name );
		
		self::find( $id )->update(['video_screen' => $file_name]);
    }

    // Upload video file
    public static function upload_video( $file, $id )
    {
    	if( $old_video = self::find( $id )->video_file )
			\File::delete( public_path() . '/uploads/projects/video/' . $old_video );
		
		$file_name = time() . '_' . \Slug::make(basename($file->getClientOriginalName(), '.' . $file->getClientOriginalExtension())) . '.' . $file->getClientOriginalExtension();
		
		$file->move( public_path() . '/uploads/projects/video/', $file_name );

		self::find( $id )->update(['video_file' => $file_name]);
    }

    // All images project
	public function images()
	{
		return $this->hasMany( 'App\Models\ProjectImage' , 'project_id' );
	}

	// All images project JSON
	public static function json_images( $images )
	{
		$images_json = [];
		if( count($images) )
		{
			foreach( $images as $item )
			{
				$images_json[] = [
									'src'  => \URL::to('uploads/projects/images/original/' . $item->image),
									'opts' => ['caption' => $item->caption]
								 ];
			}
		}
		return json_encode($images_json);
	}

	// Project youtube video code
	public static function video_code( $video_url )
	{
		parse_str( parse_url($video_url, PHP_URL_QUERY), $code );
		return $code['v'];
	}

	// Projects JSON data Google Map
	public static function json_points_map()
	{
		$projects = self::select('object_point', 'name_' . \App::getLocale(), 'slug' )
					  	->whereVisible( 1 )
					  	->get();

		$points_json = [];
		if( count($projects) )
		{
			foreach( $projects as $project )
			{
				if( $project->object_point )
				{
					$point = explode(' ', $project->object_point);

					$points_json[] = [
										'location' => ['lat' => trim($point[0]), 'lng' => trim($point[1])],
										'title'	   => $project->name,
										'url'	   => \LaravelLocalization::getLocalizedURL( \App::getLocale(), '/project/' . $project->slug )
									 ];
				}
			}
		}
		return json_encode($points_json);
	}
	
	// Project check honors
	public static function check_project_honors( $images )
	{
		$flag = FALSE;
		
		if( count($images) )
		{
			foreach( $images as $image )
			{
				if( $image->type == 'honors' )
				{
					$flag = TRUE;
				}
			}
		}
		
		return $flag;
	}
}

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $table = 'as_settings';
	
	protected $guarded = [];
	
	// Адрес
	public function getAddressAttribute()
	{
		$locale = \App::getLocale();
		$column = 'address_' . $locale;
		return $this->{$column};
    }
}

app/Http/Controllers/Frontend/BaseController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Menu;
use App\Models\Setting;
use App\Models\MainPage;

class BaseController extends Controller
{
	protected $request;
	
	public function __construct(){

		$this->request = \App::make('Illuminate\Http\Request');

		// Current locale
		$locale = \App::getLocale();

		// All languages
		$langs = \LaravelLocalization::getSupportedLocales();
		$langs = array_keys( $langs );
		$langs = array_values(array_sort($langs, function( $value ) use ( $locale ){	
			return ($locale != $value);
		}));
		
		// Menu
		$menu = Menu::all()->toHierarchy();

		// Settings
		$settings = Setting::find(1);

		view()->share(compact(['menu', 'settings', 'locale', 'langs']));
	}
}

app/Http/Controllers/Frontend/CategoriesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Project;
use App\Models\ProjectCategory;

class CategoriesController extends BaseController
{
    public function __contstruct()
    {
    	parent::__contstruct();
    }

    // Show category
    public function getIndex( Request $request, $slug )
    {
		$project_type = 'all';
		if( $request->get('type') )
			$project_type = $request->get('type');

		// Projects
		$projects = Project::with(['images' => function( $query ){
									$query->whereType('slider')
										  ->whereActive( 1 )
										  ->whereVisible( 1 );
								 }]);

		if( $slug != 'projects-all' )
		{
			$page = ProjectCategory::whereSlug( $slug )->firstOrFail();

			$projects = $projects->whereCategoryId( $page->id )
								 ->whereVisible( 1 );
		}
		else
		{
			$page = Page::whereSlug( $slug )->firstOrFail();

			$projects = $projects->whereVisible( 1 );
		}

		if( $project_type != 'all' )
			$projects = $projects->whereType( $project_type );

		$projects = $projects->orderBy('position')
							 ->get();

		// Types
		$types = [
    				'appartment' => trans('design.filter_apartment'), 
    				'house' 	 => trans('design.filter_house'), 
    				'office' 	 => trans('design.filter_office'), 
    				'all' 		 => trans('design.filter_all')
    			 ];

		// Background url
		$background_url = '';
		if( isset($page->image) && $page->image )
			$background_url = \URL::to('uploads/pages/images/' . $page->image);
		elseif( isset($page->video_screen) && $page->video_screen )
			$background_url = \URL::to('uploads/projects_categories/video/screenshots/' . $page->video_screen);
		else
			$background_url = 'http://placehold.it/1920x645?text=No background';

		// Video file
		$video_file = '';
		if( isset($page->video_file) && $page->video_file )
		{
			if( isset($page->image) )
				$video_file = \URL::to('uploads/pages/video/' . $page->video_file);
			else
				$video_file = \URL::to('uploads/projects_categories/video/' . $page->video_file);
		}

		// Points map
		$points = Project::json_points_map();

		return view('frontend.showCategory', compact(['page', 'projects', 'types', 'background_url', 'video_file', 'points']));
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Project;
use App\Models\MainPage;

class HomeController extends BaseController
{
    public function __contstruct(){
    	parent::__contstruct();
    }

    // Show main page
    public function getIndex(){
        
		$page = Page::whereSlug(' ')->firstOrFail();

		$main_page = MainPage::find( 1 );

		// Images
		$images = [
					'section_2_photo'	=> '480x480',
					'section_3_image_1' => '360x265',
					'section_3_image_2' => '360x265',
					'section_3_image_3' => '360x265',
					'section_3_image_4' => '360x265',
					'section_6_photo'	=> '649x274' 
				  ];

		foreach( $images as $key => $value )
		{
			if( $main_page->{$key} )
				$main_page->{$key} = \URL::to('uploads/main_page/' . $main_page->{$key});
			else
				$main_page->{$key} = 'http://placehold.it/' . $value . '?text=No photo';
		}

		$projects_left = Project::with(['images' => function( $query ){
										$query->whereType('slider')
											  ->whereActive( 1 )
											  ->whereVisible( 1 );
								  }])
								->whereVisibleMainThumbs( 1 )
								->whereVisible( 1 )
								->orderBy('position')
								->take( 3 )
								->get();

		$projects_slider = Project::whereVisibleMainSlider( 1 )
								  ->whereVisible( 1 )
								  ->orderBy('position')
								  ->get();

		$project_honors = Project::with(['images' => function( $query ){
										$query->whereType('honors')
											  ->whereVisible( 1 )
											  ->orderBy('position');
								  }])
								->whereVisibleMainHonors( 1 )
								->whereVisible( 1 )
								->first();

		return view('frontend.Main', compact(['page', 'main_page', 'projects_left', 'projects_slider', 'project_honors']));
    }
}

resources/views/frontend/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        @if( isset( $page->meta_title ) )
          <title>{{ $page->meta_title }}</title>
        @endif
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        @if( isset( $page->meta_keywords ) )
          <meta name="keywords" content="{{ $page->meta_keywords }}">
        @endif
        @if( isset( $page->meta_description ) )
          <meta name="description" content="{{ $page->meta_description }}">
        @endif
		<!-- Styles -->
		@section('styles')
			<link href="{{ asset('css/app.css') }}" media="all" rel="stylesheet"  />
		@show

		<!-- Disabled right mouse click -->
		<script>
			document.oncontextmenu = new Function("return false;");
		</script>
    </head>

      <body oncontextmenu="return false" class="is-preloader-visible">
        <script type="text/javascript">
          if (sessionStorage.getItem('preloader') || location.pathname !== '/') {
            document.body.classList.remove('is-preloader-visible');
          }
        </script>
        @include('frontend.partials.preloader')

        <audio class="js-audio-hover" >
          <source src="{{ URL::to('audio/hover.mp3') }}" type="audio/mpeg">
        </audio>

        <div class="wrapper" >
          @include('frontend.partials.menu')



  		    @yield('main')

        </div>

  		<!-- Scripts -->
  		@section('scripts')
  			<script src="{{ asset('js/app.js') }}"></script>
  		@show
    </body>
</html>

resources/views/frontend/showProject.blade.php
@extends('frontend.layout')

@section('main')

	<section class="section section--inner   is-section-preanimated is-transition-enabled"  >

		<div class="cover">
			<div class="cover__items">
				<div class="cover__item cover__item--left-top">
					<a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/' ) }}" class="logo-text">
						<img src="{{ URL::to('images/logo-text.png') }}" alt="" />
					</a>
					@include('frontend.partials.audio')

					@include('frontend.partials.lang')
				</div>

				<div class="cover__item cover__item--center-bottom">
					<button class="btn btn--square btn--dashed-bottom  is-animated js-scroll-down"><span class="fi-arrow-down scroll-down"></span></button>
				</div>


				<div class="cover__item cover__item--left-bottom">
					<h2 class="cover__heading">{{ $page->name }}</h2>
				</div>

				<div class="cover__item cover__item--right-bottom">
					<div class="btn-group btn-group--end">
						@if( $prev_project_url = (isset($prev_next_urls[0]) ? $prev_next_urls[0] : '') )
							<a href="{{ $prev_project_url }}" class="btn btn--square"><i class="fi-arrow-left"></i></a>
						@endif
						@if( $next_project_url = (isset($prev_next_urls[1]) ? $prev_next_urls[1] : '') )
							<a href="{{ $next_project_url }}" class="btn btn--square"><i class="fi-arrow-right"></i></a>
						@endif
					</div>
				</div>
			</div>

			<div class="cover__media" style="background-image: url('{{ $background_url }}');">
				@if( $video_file )
					<video muted loop preload="none" id="inner-video">
						<source type="video/mp4" src="{{ $video_file }}">
					</video>
				@endif
			</div>

    	</div>

		<div class="section__line"></div>
  </section>

	<div class="bg-dark">
		<div class="project js-waypoint is-preanimated is-transition-enabled" data-transitionend=".project__text">
			<div class="project__header">
				<div class="project__tags">
					<a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/' ) }}" class="project__tag">{{ trans('design.home') }}</a>
					<a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/category/' . $category->slug ) }}" class="project__tag">{{ $category->name }}</a>
					<span class="project__tag">{{ $page->name }}</span>
				</div>
			</div>
			<div class="project__content">
				<div class="project__image">
					@if( count($page->images) )
						@foreach( $page->images as $item )
							@if( $item->type == 'slider' && $item->active == 1 )
								<img src="{{ URL::to('uploads/projects/images/middle/' . $item->image) }}" alt="{{{ !empty( $item->alt ) ? $item->alt : $page->name }}}" @if( $item->title ) title="{{{ $item->title }}}" @endif />
								<?php break; ?>
							@endif
						@endforeach
					@else
						<img src="http://placehold.it/576x384?text=No image" alt="{{{ $page->name }}}" />
					@endif
				</div>
				<div class="project__desc">
					<div class="project__info">
						@if( $page->object )
							<p>{{ trans('design.an_object') }}: <span class="c-gray">{{ $page->object }}</span></p>
						@endif
						@if( $page->location )
							<p>{{ trans('design.location') }}: <span class="c-gray">{{ $page->location }}</span></p>
						@endif
						@if( $page->space )
							<p>{{ trans('design.space') }}: <span class="c-gray">{{ $page->space }}</span></p>
						@endif
						@if( $page->client )
							<p>{{ trans('design.client') }}: <span class="c-gray">{{ $page->client }}</span></p>
						@endif
						@if( $page->object_year )
							<p>{{ trans('design.object_year') }}: <span class="c-gray">{{ $page->object_year }}</span></p>
						@endif
						@if( $page->photographer )
							<p>{{ trans('design.photographer') }}: <span class="c-gray">{{ $page->photographer }}</span></p>
						@endif
					</div>
					@if( $page->annotation )
						<div class="project__text">
							<p>
								{{ $page->annotation }}
							</p>
						</div>
					@endif
				</div>
			</div>
		</div>

		@if( App\Models\Project::check_project_honors( $page->images ) )
			<div class="rewards-section js-waypoint is-preanimated is-transition-enabled" data-offset="70%">
				<h3 class="rewards-section__heading">{{ trans('design.rewards') }}</h3>

				<div class="rewards-section__content rewards-short">
					<div class="rewards-short__text">
						<h5 class="rewards-short__title">{{ trans('design.rewards') }}:</h5>
						@foreach( $page->images as $item )
							@if( $item->type == 'honors' && $item->caption )
								<p>{{ $item->caption }}</p>
							@endif
						@endforeach
					</div>

					@foreach( $page->images as $item )
						@if( $item->type == 'honors' )
							@if( $item->url )
								<a href="{!! $item->url !!}" target="_blank" class="rewards-short__image">
							@else
								<div class="rewards-short__image">
							@endif
								<img src="{{ URL::to('uploads/projects/images/thumbnail/' . $item->image) }}" alt="{{{ !empty( $item->alt ) ? $item->alt : $item->caption }}}" @if( $item->title ) title="{{{ $item->title }}}" @endif />
							@if( $item->url )
								</a>
							@else
								</div>
							@endif
						@endif
					@endforeach
					
				</div>
			</div>
		@endif

		<div class="photo-slider">
			<h3 class="photo-slider__heading">{{ trans('design.about_project') }}</h3>

			@if( $page->body_slider )
				<div class="photo-slider__text">
					{!! $page->body_slider !!}
				</div>
			@endif

			@if( count($page->images) )
				<div class="photo-slider__body">
					<div class="photo-slider__slider js-ps">
						@foreach( $page->images as $item )
							@if( $item->type == 'slider' )
								<div data-caption="{{ $item->caption }}">
									<div class="photo-slider__img">
										<div>
											<img src="{{ URL::to('uploads/projects/images/original/' . $item->image) }}" alt="{{{ !empty( $item->alt ) ? $item->alt : '' }}}" @if( $item->title ) title="{{{ $item->title }}}" @endif />
										</div>
									</div>
								</div>
							@endif
						@endforeach
					</div>
					<a href="#" class="photo-slider__nav photo-slider__nav--prev btn btn--square js-ps-prev"><i class="fi-arrow-left"></i></a>
					<a href="#" class="photo-slider__nav photo-slider__nav--next btn btn--square js-ps-next"><i class="fi-arrow-right"></i></a>
					{{--
					<div class="photo-slider__footer">
						<a href="#" class="btn btn--square js-ps-prev"><i class="fi-arrow-left"></i></a>
						<div class="photo-slider__desc">
							<div class="photo-slider__counter js-ps-status"></div>
							<div class="photo-slider__caption js-ps-caption"></div>
						</div>
						<a href="#" class="btn btn--square js-ps-next"><i class="fi-arrow-right"></i></a>
					</div>
					--}}
				</div>
			@endif

		</div>

		<div class="masonry">

			@if( $page->body_gallery )
				<div class="masonry__text">
					{!! $page->body_gallery !!}
				</div>
			@endif

			@if( count($page->images) )
				<div class="masonry__body js-waypoint is-preanimated is-transition-enabled" data-transitionend=".masonry__item:last-child">
					@foreach( $page->images as $item )
						@if( $item->type == 'gallery' )
							<div class="masonry__item">
								<a href="{{ URL::to('uploads/projects/images/original/' . $item->image) }}" class="masonry__link" data-fancybox="masonry">
									<img src="{{ URL::to('uploads/projects/images/middle/' . $item->image) }}" alt="{{{ !empty( $item->alt ) ? $item->alt : '' }}}" @if( $item->title ) title="{{{ $item->title }}}" @endif />
								</a>
							</div>
						@endif
					@endforeach
				</div>
			@endif
		</div>

		@if( $page->video_youtube )
			<div class="yt">
				<iframe src="https://www.youtube.com/embed/{!! App\Models\Project::video_code( $page->video_youtube ) !!}" frameborder="0" allowfullscreen></iframe>
			</div>
		@endif

		@if( $page->body_video )
			<div class="text">
				{!! $page->body_video !!}
			</div>
		@endif

	</div>

	@include('frontend.partials.footer', ['footerClass' => 'footer--dark'])
@endsection