app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Templates
Route::pattern('id', '[0-9]+');
Route::pattern('page_url', '[0-9a-z-_]+');

// Dashboard
Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => 'auth'], function(){

	// Main page
	Route::get('/', 'AdminHomeController@getIndex');
	Route::post('/', 'AdminHomeController@postIndex');
	Route::post('/upload-image', 'AdminHomeController@postUploadImage');

	// Other controllers
	Route::controllers([
        'settings'				=> 'AdminSettingsController',
        'menu'					=> 'AdminMenuController',
        'pages'					=> 'AdminPagesController',
        'projects-categories'	=> 'AdminProjectsCategoriesController',
        'projects'				=> 'AdminProjectsController',
        'publications'			=> 'AdminPublicationsController',
        'about-page'			=> 'AdminAboutPageController',
        'feedbacks'				=> 'AdminFeedbacksController',
        'users'					=> 'AdminUsersController',
    ]);

	// Logout
	Route::get('auth/logout', 'Auth\AuthController@logout');
});

// Default auth
Route::controllers([
	'auth' 		=> 'Auth\AuthController',
	'password' 	=> 'Auth\PasswordController',
]);

// Frontend
Route::group(['namespace' => 'Frontend', 'prefix' => LaravelLocalization::setLocale()], function(){

	// Main page
	Route::get('/', 'HomeController@getIndex');

	// Projects category
	Route::get('/category/{page_url}', 'CategoriesController@getIndex');

	// Projects media
	foreach( ['photo', 'video', 'honors'] as $route )
	{
		Route::get('/projects-' . $route, 'ProjectsController@getMedia');
	}

	// Project
	Route::get('/project/{page_url}', 'ProjectsController@getProject');

	// Publications
	Route::get('/publications', 'PublicationsController@getIndex');

	// Page about
	Route::get('/about', 'PagesController@getAbout');

	// Page contacts
	Route::get('/contacts', 'PagesController@getContacts');
	Route::post('/contacts', 'PagesController@postContacts');

	// Other pages
	Route::get('/{page_url}', 'PagesController@getIndex');
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Baum\Node;

class Menu extends Node
{
	protected $table = 'as_menu';
	
	protected $guarded = [];

	// Название меню
	public function getNameAttribute()
	{
		$locale = \App::getLocale();
		$column = 'name_' . $locale;
		return $this->{$column};
    }

    # Frontend

    // Item menu url
    public static function itemMenuURL( $url )
    {
    	switch( $url )
    	{
			case '':
				$url = \LaravelLocalization::getLocalizedURL( \App::getLocale(), '/' );
			break;
			case '#':
				$url = '#';
			break;
			default:
				$url = \LaravelLocalization::getLocalizedURL( \App::getLocale(), $url );
		}

		return $url;
    }

    // Active menu element
    public static function itemMenuActive( $url, $page_id = null )
    {
    	$class = '';
    	
    	$localized_url = \LaravelLocalization::getLocalizedURL( \App::getLocale(), $url );
    	$localized_current_url = \LaravelLocalization::getLocalizedURL( \App::getLocale() );

        // if GET parametr?
        if( strpos($localized_current_url, '?') !== false )
            $localized_current_url = strtok($localized_current_url, '?');

    	// $page_id -> 2 - Home page
    	if( ($localized_url == $localized_current_url && $url != '#' && $url != '') || ($page_id == 2 && !$url) )
    		$class = 'is-active';

    	return $class;
    }
}

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $table = 'as_settings';
	
	protected $guarded = [];
	
	// Адрес
	public function getAddressAttribute()
	{
		$locale = \App::getLocale();
		$column = 'address_' . $locale;
		return $this->{$column};
    }
}

app/Http/Controllers/Frontend/BaseController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Menu;
use App\Models\Setting;
use App\Models\MainPage;

class BaseController extends Controller
{
	protected $request;
	
	public function __construct(){

		$this->request = \App::make('Illuminate\Http\Request');

		// Current locale
		$locale = \App::getLocale();

		// All languages
		$langs = \LaravelLocalization::getSupportedLocales();
		$langs = array_keys( $langs );
		$langs = array_values(array_sort($langs, function( $value ) use ( $locale ){	
			return ($locale != $value);
		}));
		
		// Menu
		$menu = Menu::all()->toHierarchy();

		// Settings
		$settings = Setting::find(1);

		view()->share(compact(['menu', 'settings', 'locale', 'langs']));
	}
}

app/Http/Controllers/Frontend/CategoriesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Project;
use App\Models\ProjectCategory;

class CategoriesController extends BaseController
{
    public function __contstruct()
    {
    	parent::__contstruct();
    }

    // Show category
    public function getIndex( Request $request, $slug )
    {
		$project_type = 'all';
		if( $request->get('type') )
			$project_type = $request->get('type');

		// Projects
		$projects = Project::with(['images' => function( $query ){
									$query->whereType('slider')
										  ->whereActive( 1 )
										  ->whereVisible( 1 );
								 }]);

		if( $slug != 'projects-all' )
		{
			$page = ProjectCategory::whereSlug( $slug )->firstOrFail();

			$projects = $projects->whereCategoryId( $page->id )
								 ->whereVisible( 1 );
		}
		else
		{
			$page = Page::whereSlug( $slug )->firstOrFail();

			$projects = $projects->whereVisible( 1 );
		}

		if( $project_type != 'all' )
			$projects = $projects->whereType( $project_type );

		$projects = $projects->orderBy('position')
							 ->get();

		// Types
		$types = [
    				'appartment' => trans('design.filter_apartment'), 
    				'house' 	 => trans('design.filter_house'), 
    				'office' 	 => trans('design.filter_office'), 
    				'all' 		 => trans('design.filter_all')
    			 ];

		// Background url
		$background_url = '';
		if( isset($page->image) && $page->image )
			$background_url = \URL::to('uploads/pages/images/' . $page->image);
		elseif( isset($page->video_screen) && $page->video_screen )
			$background_url = \URL::to('uploads/projects_categories/video/screenshots/' . $page->video_screen);
		else
			$background_url = 'http://placehold.it/1920x645?text=No background';

		// Video file
		$video_file = '';
		if( isset($page->video_file) && $page->video_file )
		{
			if( isset($page->image) )
				$video_file = \URL::to('uploads/pages/video/' . $page->video_file);
			else
				$video_file = \URL::to('uploads/projects_categories/video/' . $page->video_file);
		}

		// Points map
		$points = Project::json_points_map();

		return view('frontend.showCategory', compact(['page', 'projects', 'types', 'background_url', 'video_file', 'points']));
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Project;
use App\Models\MainPage;

class HomeController extends BaseController
{
    public function __contstruct(){
    	parent::__contstruct();
    }

    // Show main page
    public function getIndex(){
        
		$page = Page::whereSlug(' ')->firstOrFail();

		$main_page = MainPage::find( 1 );

		// Images
		$images = [
					'section_2_photo'	=> '480x480',
					'section_3_image_1' => '360x265',
					'section_3_image_2' => '360x265',
					'section_3_image_3' => '360x265',
					'section_3_image_4' => '360x265',
					'section_6_photo'	=> '649x274' 
				  ];

		foreach( $images as $key => $value )
		{
			if( $main_page->{$key} )
				$main_page->{$key} = \URL::to('uploads/main_page/' . $main_page->{$key});
			else
				$main_page->{$key} = 'http://placehold.it/' . $value . '?text=No photo';
		}

		$projects_left = Project::with(['images' => function( $query ){
										$query->whereType('slider')
											  ->whereActive( 1 )
											  ->whereVisible( 1 );
								  }])
								->whereVisibleMainThumbs( 1 )
								->whereVisible( 1 )
								->orderBy('position')
								->take( 3 )
								->get();

		$projects_slider = Project::whereVisibleMainSlider( 1 )
								  ->whereVisible( 1 )
								  ->orderBy('position')
								  ->get();

		$project_honors = Project::with(['images' => function( $query ){
										$query->whereType('honors')
											  ->whereVisible( 1 )
											  ->orderBy('position');
								  }])
								->whereVisibleMainHonors( 1 )
								->whereVisible( 1 )
								->first();

		return view('frontend.Main', compact(['page', 'main_page', 'projects_left', 'projects_slider', 'project_honors']));
    }
}

app/Http/Controllers/Frontend/PagesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Feedback;
use App\Models\Setting;
use App\Models\AboutPage;

class PagesController extends BaseController
{
    public function __contstruct()
    {
    	parent::__contstruct();
    }

    // Page default
    public function getIndex( $slug )
    {
		$page = Page::whereSlug( $slug )->firstOrFail();

		// Background
		if( $page->image )
			$page->image = \URL::to('uploads/pages/images/' . $page->image);
		else
			$page->image = 'http://placehold.it/1920x645?text=No background';

		return view('frontend.showPage', compact(['page']));
    }

    // Page about
    public function getAbout()
    {
		$page = Page::whereSlug('about')->firstOrFail();

		$about_page = AboutPage::find( 1 );

        // Background
		if( $page->image )
			$page->image = \URL::to('uploads/pages/images/' . $page->image);
		else
			$page->image = 'http://placehold.it/1920x645?text=No background';

		return view('frontend.showPageAbout', compact(['page', 'about_page']));
    }

    // Page contacts
    public function getContacts()
    {
		$page = Page::whereSlug('contacts')->firstOrFail();

		// Background
		if( $page->image )
			$page->image = \URL::to('uploads/pages/images/' . $page->image);
		else
			$page->image = 'http://placehold.it/1920x645?text=No background';

		return view('frontend.showPageContacts', compact(['page']));
    }

    // Page contacts action
    public function postContacts( Request $request  )
    {
    	if( $request->ajax() )
        {
	    	$validation_fields = [
	    							'name' 	  => 'required', 
	    							'email'	  => 'required|email', 
	    							'phone'	  => 'required', 
	    							'comment' => 'required|min:10'
	    						 ];

			$fields = $request->except(['_token']);

            $validator = \Validator::make( $fields, $validation_fields );

            if( !$validator->fails() )
            {
                Feedback::create( $fields );

                $email = Setting::find( 1 )->email;

                \Mail::send('emails.feedback', $fields, function( $message ) use ( $email ){
                    $message->to($email, 'Grabovskiy')->subject('Обратная связь');
                });

                return \Response::json(['success' => trans('design.message_success')]);
            }
            else
                return \Response::json(['errors'  => $validator->errors()->getMessages()]);
	    }
    }
}

app/Http/Controllers/Frontend/ProjectsController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Project;
use App\Models\ProjectCategory;

class ProjectsController extends BaseController
{
    public function __contstruct()
    {
    	parent::__contstruct();
    }

    // Projects media
    public function getMedia( Request $request )
    {
		// URL page
		$slug = \LaravelLocalization::getNonLocalizedURL();
		$slug = strtok($slug, '?');
		$slug = str_replace([url(), '/'], '', $slug);

		switch( $slug )
		{
			case 'projects-photo':
				$position = 'position_photos';
				$view = 'frontend.showProjectsPhoto';
				$images_type = 'slider';
			break;
			case 'projects-video':
				$position = 'position_videos';
				$view = 'frontend.showProjectsVideo';
				$images_type = 'slider';
			break;
			case 'projects-honors':
				$position = 'position_honors';
				$view = 'frontend.showProjectsHonors';
				$images_type = 'honors';
			break;
		}

		$page = Page::whereSlug( $slug )->firstOrFail();

		$project_type = 'all';
		if( $request->get('type') )
			$project_type = $request->get('type');

		// Projects
		$projects = Project::with(['images' => function( $query ) use ( $images_type ){
									if( $images_type != 'honors' )
										$query->whereType( $images_type )
											  ->whereVisible( 1 )
											  ->orderBy('position');
									else
										$query->whereVisible( 1 )
											  ->orderBy('position');
								 }])
						   ->whereVisible( 1 );

		if( $project_type != 'all' )
			$projects = $projects->whereType( $project_type );

		$projects = $projects->orderBy( $position )
							 ->get();

		// Types
		$types = [
    				'appartment' => trans('design.filter_apartment'), 
    				'house' 	 => trans('design.filter_house'), 
    				'office' 	 => trans('design.filter_office'), 
    				'all' 		 => trans('design.filter_all')
    			 ];

		// Background url
		$background_url = '';
		if( isset($page->image) && $page->image )
			$background_url = \URL::to('uploads/pages/images/' . $page->image);
		else
			$background_url = 'http://placehold.it/1920x645?text=No background';

		// Video file
		$video_file = '';
		if( isset($page->video_file) && $page->video_file )
			$video_file = \URL::to('uploads/pages/video/' . $page->video_file);

		// Points map
		$points = Project::json_points_map();

		return view($view, compact(['page', 'projects', 'types', 'background_url', 'video_file', 'points']));
    }

    // Project
    public function getProject( $slug )
    {
    	$page = Project::with(['images' => function( $query ){
									$query->whereVisible( 1 )
									      ->orderBy('position');
						   }])
    				   ->whereSlug( $slug )
    				   ->firstOrFail();

    	// Current category project
    	$category = ProjectCategory::find( $page->category_id );

    	// Prev/Next projects
    	$next_project_id = Project::where('id', '>', $page->id)
    							  ->whereVisible( 1 )
    							  ->min('id');
		$prev_project_id = Project::where('id', '<', $page->id)
								  ->whereVisible( 1 )
								  ->max('id');

		$pn_ids = [];
		if( $next_project_id )
			$pn_ids[] = $next_project_id;
		else
			$pn_ids[] = Project::whereVisible( 1 )
							   ->orderBy('id', 'ASC')
							   ->first()
							   ->id;
		if( $prev_project_id )
			$pn_ids[] = $prev_project_id;
		else
			$pn_ids[] = Project::whereVisible( 1 )
							   ->orderBy('id', 'DESC')
							   ->first()
							   ->id;

		$pn_ids_str = implode(',', $pn_ids);

		$prev_next_projects = Project::select('slug')
									 ->whereIn('id', $pn_ids)
							 		 ->whereVisible( 1 )
							 		 ->orderBy( \DB::raw('FIELD(id, ' . $pn_ids_str . ')'), 'DESC' )
									 ->get();

		$prev_next_urls = [];
		if( count($prev_next_projects) )
		{
			foreach( $prev_next_projects as $pn )
			{
				$prev_next_urls[] = \LaravelLocalization::getLocalizedURL( \App::getLocale(), '/project/' . $pn->slug );
			}
		}

    	// Background url
		$background_url = '';
		if( isset($page->video_screen) && $page->video_screen )
			$background_url = \URL::to('uploads/projects/video/screenshots/' . $page->video_screen);
		else
			$background_url = 'http://placehold.it/1920x645?text=No background';

		// Video file
		$video_file = '';
		if( isset($page->video_file) && $page->video_file )
			$video_file = \URL::to('uploads/projects/video/' . $page->video_file);

    	return view('frontend.showProject', compact(['page', 'category', 'background_url', 'video_file', 'prev_next_urls']));
    }
}

app/Http/Controllers/Frontend/PublicationsController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Frontend\BaseController;

use App\Models\Page;
use App\Models\Publication;

class PublicationsController extends BaseController
{
    public function __contstruct()
    {
    	parent::__contstruct();
    }

    public function getIndex()
    {
		$page = Page::whereSlug('publications')->firstOrFail();

		$publications = Publication::whereVisible( 1 )
								   ->orderBy('position')
								   ->get();

		// Background
		if( $page->image )
			$page->image = \URL::to('uploads/pages/images/' . $page->image);
		else
			$page->image = 'http://placehold.it/1920x645?text=No background';

		return view('frontend.showPublications', compact(['page', 'publications']));
    }
}

resources/views/frontend/partials/audio.blade.php
<div class="audio">
  <button class="audio__btn btn btn--square js-audio-btn">
    {{-- App\Helpers::getFile('images/eq.svg') --}}
    <div class="bar-c">
      <div id="bar-1" class="bar"></div>
      <div id="bar-2" class="bar"></div>
      <div id="bar-3" class="bar"></div>
      <div id="bar-4" class="bar"></div>
      <div id="bar-5" class="bar"></div>
      <div id="bar-6" class="bar"></div>
    </div>
  </button>

  <audio class="js-audio" preload="none" data-keepplaying>
    <source src="{{ URL::to('audio/audio.mp3') }}" type="audio/mpeg">
  </audio>
</div>

resources/views/frontend/partials/copyright.blade.php
<div class="copyright">
  <p>&copy;Alexandr Grabovskiy {{ date('Y') }}. <br>{{ trans('design.rights_reserved') }}.</p>
  <p class="anim-end">{{ trans('design.copying_prohibited') }}.</p>
</div>

resources/views/frontend/partials/footer.blade.php
<footer class="footer {{$footerClass or ''}}">
  <div class="footer__left">
    <a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/category/projects-all' ) }}" class="btn btn--dashed-left is-animated">{{ trans('design.all_projects') }}</a>
  </div>

  <div class="footer__center">
    <p>{{ trans('design.footer_slogan') }}</p>
    <img src="{{ URL::to('images/footer-logo.png') }}" width="180" alt="" />
  </div>

  <div class="footer__right">
    <ul class="contact">
      @if( $settings->email )
        <li class="contact__item">
          <a href="mailto:{{ $settings->email }}" class="contact__link"><i class="fi-mail"></i>{{ $settings->email }}</a>
        </li>
      @endif
      @if( $settings->phone )
        <li class="contact__item">
          <a href="tel:{{ str_replace(['(', ')', ' ', '-'], '', $settings->phone) }}" class="contact__link"><i class="fi-phone"></i>{{ $settings->phone }}</a>
        </li>
      @endif
      @if( $settings->address )
        <li class="contact__item">
          <span class="contact__link"><i class="fi-pin"></i>{{ $settings->address }}</span>
        </li>
      @endif
    </ul>

    <?php $socialClass =  isset($socialClass) ? $socialClass : ''; ?>
    @include('frontend.partials.social', ['socialClass' => $socialClass ])
  </div>

  @include('frontend.partials.copyright')
</footer>

resources/views/frontend/partials/lang.blade.php
<div class="lang js-lang">
  @if( count($langs) )
  	@foreach( $langs as $lang )
      <a href="@if( $lang == $locale ){{ LaravelLocalization::getNonLocalizedURL() }}@else{{ LaravelLocalization::getLocalizedURL( $lang ) }}@endif" class="lang__btn btn btn--square @if( $lang == $locale ) is-active @endif">{{ $lang }}</a>
  	@endforeach
  @endif
</div>

resources/views/frontend/partials/map.blade.php
<script type="text/javascript">
  var agMapData = [
      {
        location : {
          lat : -34.397,
          lng : 150.644
        },
        title : 'House in Dnipro',
        url : '#'
      },
      {
        location : {
          lat : -35.397,
          lng : 151.644
        },
        title : 'House in Forest',
        url : '#'
      }
    ];
</script>
<section class="map">
  <header class="map__header">
    <h2 class="map__heading"><span>places on the map</span> with the completed projects</h2>
  </header>

  <div class="map__content">
    <div id="map"></div>
  </div>

  <footer class="map__footer">
    <h3>Давайте встретимся</h3>
    <p>Вы можете связаться с нами любым удобным способом</p>
  </footer>
</section>

resources/views/frontend/partials/menu.blade.php
<div class="menu__open is-invisible">
  <button class="btn btn--square js-menu-btn">
    <span class="menu__icon">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </span>
  </button>

  <div class="scrollup">
    <button class="btn btn--square js-scroll-up is-invisible"><span class="fi-arrow-up"></span></button>
  </div>
</div>

<div class="menu">
  <div class="menu__inner">
    <a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/' ) }}" class="menu__logo">
      <img src="{{ URL::to('images/menu-logo.png') }}" alt="" />
    </a>

    <nav class="menu__nav">
      @if( count($menu) )
        <ul class="menu__list">
          @foreach( $menu as $menu_item )
            @if( $menu_item->slug != 'publications' )
				<li class="menu__item">
				  <a href="{{ App\Models\Menu::itemMenuURL( $menu_item->slug ) }}" class="menu__link {{ App\Models\Menu::itemMenuActive( $menu_item->slug, $page->id ) }}">{{ $menu_item->name }}</a>
				  @if( count($menu_item->children) )
					<ul class="menu__sub">
					  @foreach( $menu_item->children as $child_item )
						<li class="menu__subitem">
						  <a href="{{ App\Models\Menu::itemMenuURL( $child_item->slug ) }}" class="menu__link">{{ $child_item->name }}</a>
						</li>
					  @endforeach
					</ul>
				  @endif
				</li>
			@endif
          @endforeach
        </ul>
      @endif
    </nav>

    <button class="menu__close btn btn--square js-menu-close"><i class="fi-close"></i></button>
  </div>


  <div class="menu__overlay overlay js-menu-close">
    <div class="overlay__item overlay__item--black"></div>
    <div class="overlay__item overlay__item--green"></div>
  </div>
</div>

resources/views/frontend/partials/projects.blade.php
<div class="projects">
  <button class="projects__close btn btn--square js-projects-close"><i class="fi-close"></i></button>

  <div class="projects__body">
    <div class="projects__list">
      
      @foreach( $projects_left as $project )
        <a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/project/' . $project->slug ) }}" class="projects__item">
          <span class="projects__title">{{ $project->name }}</span>
          @if( count($project->images) )
            @foreach( $project->images as $pi )
              <img src="{{ URL::to('uploads/projects/images/thumbnail/' . $pi->image) }}" alt="{{{ !empty( $pi->alt ) ? $pi->alt : $project->name }}}" @if( $pi->title ) title="{{{ $pi->title }}}" @endif />
              <?php break; ?>
            @endforeach
          @else
            <img src="http://placehold.it/152x101?text=No image" alt="{{{ $project->name }}}" /> 
          @endif
        </a>
      @endforeach

      <div class="projects__all">
        <a href="{{ LaravelLocalization::getLocalizedURL( $locale, '/category/projects-all' ) }}" class=" btn btn--dashed-left">{{ trans('design.all_projects') }}</a>
      </div>
    </div>
  </div>


  <div class="projects__overlay overlay">
    <div class="overlay__item overlay__item--black"></div>
    <div class="overlay__item overlay__item--white"></div>
    <div class="overlay__item overlay__item--green"></div>
  </div>
</div>

resources/views/frontend/partials/section-overlay.blade.php
<div class="section__overlay overlay">
  <div class="overlay__item overlay__item--black"></div>
  <div class="overlay__item overlay__item--green"></div>
</div>

resources/views/frontend/partials/social.blade.php
<div class="social {{$socialClass or ''}} js-s">
  @if( $settings->facebook )
  	<a href="{{ $settings->facebook }}" class="social__item btn btn--square" data-speed="slow"><i class="fi-facebook"></i></a>
  @endif
  @if( $settings->youtube )
  	<a href="{{ $settings->youtube }}" class="social__item btn btn--square" data-speed="medium"><i class="fi-youtube"></i></a>
  @endif
  @if( $settings->instagram )
  	<a href="{{ $settings->instagram }}" class="social__item btn btn--square" data-speed="fast"><i class="fi-instagram"></i></a>
  @endif
</div>


{{--
remove js-s and data-speed on prod
--}}